// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SINPRO.Entity;

namespace SINPRO.Migrations
{
    [DbContext(typeof(SINContext))]
    [Migration("20220112193538_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("SINPRO.Entity.DataModels.mBanner", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("inserted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("link")
                        .HasColumnType("longtext");

                    b.Property<string>("photo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("mBanner");
                });

            modelBuilder.Entity("SINPRO.Entity.DataModels.mMatch", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("firstTimeName")
                        .HasColumnType("longtext");

                    b.Property<string>("firstTimePhoto")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("inserted")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("matchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("matchTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("secondTimeName")
                        .HasColumnType("longtext");

                    b.Property<string>("secondTimePhoto")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("mMatch");
                });

            modelBuilder.Entity("SINPRO.Entity.DataModels.mNew", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("discription")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("inserted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("photo")
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("mNew");
                });

            modelBuilder.Entity("SINPRO.Entity.DataModels.mRole", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("inserted")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("parentId")
                        .HasColumnType("int");

                    b.Property<string>("resourceName")
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("mRole");
                });

            modelBuilder.Entity("SINPRO.Entity.DataModels.mUser", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("fName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("inserted")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("refershTokenExpiration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("refreshToken")
                        .HasColumnType("longtext");

                    b.Property<int>("roleId")
                        .HasColumnType("int");

                    b.Property<string>("sName")
                        .HasColumnType("longtext");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("roleId");

                    b.ToTable("mUser");
                });

            modelBuilder.Entity("SINPRO.Entity.DataModels.mUser", b =>
                {
                    b.HasOne("SINPRO.Entity.DataModels.mRole", "mRole")
                        .WithMany("mUser")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mRole");
                });

            modelBuilder.Entity("SINPRO.Entity.DataModels.mRole", b =>
                {
                    b.Navigation("mUser");
                });
#pragma warning restore 612, 618
        }
    }
}
